### ISSUE TITLE
Non-responsive images

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#49]
To resume https://github.com/openhab/openhab-docs/pull/48

I saw, that materialize is used for styling. So despite what I suggested in the other discussion, it would make more sense to rely on materialize to handle pics? http://materializecss.com/media-css.html

```css
<img class="responsive-img"...>
```
The effect is more or less the same: 
```css
img.responsive-img {max-width: 100%; height: auto;}
```
I have no experience with jekyll, would be great if somebody could quickly provide the needed change.
