### ISSUE TITLE
H4 styling missing

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#72]
H1..H3 receive styling from style.css
H4 does not and is thereby bigger and darker.

needs to be fixed in ESH and OH2 docs

linked to https://github.com/openhab/openhab-docs/issues/62

**Comment by ThomDietrich** [comment]
Also style related: violates lists

```css
section.text ul { margin: 0px 0px 20px; }
```
